### ISSUE TITLE
Latest versions run in Node 5

### ISSUE THREAD

**Issue by amir20** [leebenson/babel-preset-node5#15]
Hello,

I recently upgrade to version `^12.0.0` and noticed that my [travis build](https://travis-ci.org/amir20/phantomjs-node/jobs/183045965) stopped working. I did some investigation and saw this error

```
/Users/amirraminfar/Workspace/phantomjs-node/node_modules/babel-preset-node5/index.js:3
module.exports = function(context, opts = {}) {
                                        ^

SyntaxError: Unexpected token = (While processing preset: "/Users/amirraminfar/Workspace/phantomjs-node/node_modules/babel-preset-node5/index.js")
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/amirraminfar/Workspace/phantomjs-node/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /Users/amirraminfar/Workspace/phantomjs-node/node_modules/babel-core/lib/transformation/file/options/option-manager.js:302:17
    at Array.map (native)
npm ERR! Test failed.  See above for more details.
```

It seems that the new version doesn't work in v5 of Node. Is to be expected? 

If so, then I could use come guidance. In my [travis.yml](https://github.com/amir20/phantomjs-node/blob/master/.travis.yml) file, I test version 5, 6, 7 and latest. I am guessing the compiled version of my code works fine but to compile it I have to use a different version. I am not sure how to do that.  Perhaps, it's a bug and making `preset-node5` work in v5 is important.

**Comment by leebenson** [comment]
The `opt = {}` default syntax was introduced in 3fa087f (via PR) and according to http://node.green, that's an error in Node 5.x - so that's definitely not serving the purpose of this repo!

TBH, I haven't used this package in some time, and now that 6.x is in LTS, it's probably overdue that it be deprecated.

I personally use [babel-preset-node7](https://www.npmjs.com/package/babel-preset-node7) now and would recommend upgrading (both the package and to a newer Node version)
