### ISSUE TITLE
Alternative approach to this projects goals

### ISSUE THREAD

**Issue by balupton** [leebenson/babel-preset-node5#3]
Hey, we've been using https://github.com/bevry/esnextguardian over the year to achieve a similar goal to this. It may be of use to your module readers.

**Comment by leebenson** [comment]
Cool project. The goal of babel-preset-node5 is simply to polyfill Node 5 specifically, where we know the gaps and can polyfill them ahead of time. esnextguardian seems like a better solution for general-purpose transpiling, where the user's environment is an unknown.

I don't really have an outlet to promote alternatives, otherwise I'd stick this on the list. This lib is really just a curated wrapper of babel plugins specific to Node 5. Thanks.

**Comment by balupton** [comment]
No worries. Rock on.
